name: moi_meet_flutter_sdk
description: A flutter plugin that serves as a Moi Meet flutter SDK which provides the same user experience as the Moi Meet app.
version: 1.0.0
homepage: https://meet.aioman.org
repository: https://github.com/ANASDAVOODTK/moi-meet-flutter-sdk
documentation: https://github.com/ANASDAVOODTK/moi-meet-flutter-sdk/blob/main/README.md


environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.moi.moi_meet_flutter_sdk
        pluginClass: MoiMeetPlugin
      ios:
        pluginClass: MoiMeetPlugin
